const List<String> categories = [
  'Plumber',
  'Electrician',
  'AC Repair',
  'Carpenter',
  'Painter',
  'Cleaning',
  'RO Service',
  'Appliance Repair',
  'Mechanic',
  'Mobile Repair',
  'Computer Repair',
  'Tutor',
  'Delivery',
  'Tailor',
  'Beautician',
  'Photographer',
  'CCTV',
  'Internet / WiFi',
  'Other',
];

const List<String> businessTypes = [
  'Plumbing',
  'Electrical',
  'Cleaning & Housekeeping',
  'AC & Appliance Repair',
  'Carpentry & Furniture',
  'Painting & Waterproofing',
  'Beauty & Wellness',
  'Education & Tutoring',
  'Delivery & Logistics',
  'Photography & Events',
  'Computer & Mobile Repair',
  'Security & CCTV',
  'Internet & Networking',
  'Food & Catering',
  'Healthcare & Medical',
  'Auto & Vehicle Service',
  'Tailoring & Alterations',
  'Other Local Service',
];
