#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

show_help() {
  cat <<'EOF'
Usage: bash scripts/supabase_copy_sql.sh [options]

Builds a SQL bundle from canonical Supabase migrations for SQL Editor usage.
By default, it includes:
  - supabase/migrations/*.sql (sorted)
  - supabase/verify_realtime_setup.sql

Options:
  --with-dashboard-seed   Include supabase/seed_dashboard_demo.sql
  --with-realtime-seed    Include supabase/seed_realtime_tabs_demo.sql (implies dashboard seed)
  --with-seeds            Include both optional seed files
  --without-verify        Exclude supabase/verify_realtime_setup.sql
  --stdout                Print bundle to stdout instead of clipboard
  -h, --help              Show this help message
EOF
}

with_dashboard_seed=0
with_realtime_seed=0
with_verify=1
to_stdout=0

for arg in "$@"; do
  case "$arg" in
    --with-dashboard-seed)
      with_dashboard_seed=1
      ;;
    --with-realtime-seed)
      with_dashboard_seed=1
      with_realtime_seed=1
      ;;
    --with-seeds)
      with_dashboard_seed=1
      with_realtime_seed=1
      ;;
    --without-verify)
      with_verify=0
      ;;
    --stdout)
      to_stdout=1
      ;;
    -h|--help)
      show_help
      exit 0
      ;;
    *)
      echo "Unknown option: $arg"
      show_help
      exit 1
      ;;
  esac
done

append_file_to_bundle() {
  local relative_file="$1"
  local absolute_file="$ROOT_DIR/$relative_file"

  if [[ ! -f "$absolute_file" ]]; then
    echo "Missing SQL file: $relative_file"
    exit 1
  fi

  {
    echo
    echo "-- ============================================================"
    echo "-- BEGIN: $relative_file"
    echo "-- ============================================================"
    cat "$absolute_file"
    echo
    echo "-- END: $relative_file"
  } >> "$bundle_file"
}

migration_files=()
while IFS= read -r file; do
  migration_files+=("$file")
done < <(find "$ROOT_DIR/supabase/migrations" -maxdepth 1 -type f -name '*.sql' | sort)

if [[ "${#migration_files[@]}" -eq 0 ]]; then
  echo "No migration files found in supabase/migrations."
  exit 1
fi

bundle_file="$(mktemp "${TMPDIR:-/tmp}/supabase_sql_bundle.XXXXXX.sql")"

{
  echo "-- SQL bundle generated by scripts/supabase_copy_sql.sh"
  echo "-- Generated at: $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
  echo "-- Source: canonical supabase/migrations/*.sql"
} > "$bundle_file"

for absolute_sql_file in "${migration_files[@]}"; do
  relative_sql_file="${absolute_sql_file#$ROOT_DIR/}"
  append_file_to_bundle "$relative_sql_file"
done

if [[ "$with_dashboard_seed" -eq 1 ]]; then
  append_file_to_bundle "supabase/seed_dashboard_demo.sql"
fi

if [[ "$with_realtime_seed" -eq 1 ]]; then
  append_file_to_bundle "supabase/seed_realtime_tabs_demo.sql"
fi

if [[ "$with_verify" -eq 1 ]]; then
  append_file_to_bundle "supabase/verify_realtime_setup.sql"
fi

if [[ "$to_stdout" -eq 1 ]]; then
  cat "$bundle_file"
  rm -f "$bundle_file"
  exit 0
fi

if command -v pbcopy >/dev/null 2>&1; then
  pbcopy < "$bundle_file"
  echo "Copied SQL bundle to clipboard (pbcopy)."
elif command -v wl-copy >/dev/null 2>&1; then
  wl-copy < "$bundle_file"
  echo "Copied SQL bundle to clipboard (wl-copy)."
elif command -v xclip >/dev/null 2>&1; then
  xclip -selection clipboard < "$bundle_file"
  echo "Copied SQL bundle to clipboard (xclip)."
else
  echo "No clipboard tool found (pbcopy/wl-copy/xclip)."
  echo "Use --stdout and redirect output manually."
  rm -f "$bundle_file"
  exit 1
fi

echo "Open Supabase SQL Editor, paste, and run."
rm -f "$bundle_file"
