-- Rate limiting table for API route protection
-- Stores request counts per user/IP per route within time windows

create table if not exists public.rate_limits (
  id bigint generated by default as identity primary key,
  key text not null unique,
  request_count integer not null default 1,
  window_start bigint not null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_rate_limits_key on public.rate_limits (key);
create index if not exists idx_rate_limits_window_start on public.rate_limits (window_start);

-- Auto-cleanup expired entries
create or replace function public.cleanup_expired_rate_limits()
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  delete from public.rate_limits
  where window_start < extract(epoch from timezone('utc', now())) - 120;
end;
$$;

-- Allow service_role to manage rate_limits
grant select, insert, update, delete on public.rate_limits to service_role;
grant usage on sequence rate_limits_id_seq to service_role;
