-- OTP codes table for email verification (replaces in-memory store for serverless compat)
-- Each row represents a single OTP sent to an email address

create table if not exists public.otp_codes (
  id bigint generated by default as identity primary key,
  email text not null,
  otp text not null,
  user_id text not null,
  expires_at timestamptz not null,
  used boolean not null default false,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_otp_codes_email on public.otp_codes (email);
create index if not exists idx_otp_codes_expires_at on public.otp_codes (expires_at);

-- Auto-cleanup expired and used OTPs
create or replace function public.cleanup_expired_otps()
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  delete from public.otp_codes
  where expires_at < timezone('utc', now()) or used = true;
end;
$$;

-- Ensure service_role can manage OTP codes
grant select, insert, update, delete on public.otp_codes to service_role;
grant usage on sequence otp_codes_id_seq to service_role;

-- Refresh PostgREST schema cache so the new table is immediately visible
notify pgrst, 'reload schema';
